#!/bin/bash
############################################################
# Help                                                     #
############################################################
Help()
{
   # Display Help
   echo "Add description of the script functions here."
   echo
   echo "Syntax: scriptTemplate [-g|h|v|V]"
   echo "options:"
   echo "g     Print the GPL license notification."
   echo "h     Print this Help."
   echo "v     Verbose mode."
   echo "V     Print software version and exit."
   echo
}

############################################################
############################################################
# Main program                                             #
############################################################
############################################################
############################################################
# Process the input options. Add options as needed.        #
############################################################
# Get the options

N="TEste"


if [ $1 == '-t' ]; then

   echo entrou;
   # Talvez não seja a forma mais bonita
   # for i in $(ls | grep "[.]"); do
   #    echo "arquivo: $i";
   # done;

   # find . -maxdepth 1 -type f -printf '%f\n' | grep -v '^[.]';
   for i in *; do
      if [ -f "$i" ]; then
         # echo $i;
         if [[ "$i" == *webm ]]; then
            ffmpeg -i "$i" -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" \
            -c:v libx264 -crf 23 -preset fast \
            -c:a aac -movflags +faststart "${i%.*}.mp4"   
            rm "$i"
            echo "$i Convertido para .mp4!"; 
         fi;
      fi;
   done;




   exit;
fi




while getopts ":hf:" option; do
   case $option in
      h) # display Help
         Help;;
      
      f) # Teste
         N=$OPTARG
         echo "Convertento $N para .mp4!"
         path=`pwd`
         ffmpeg -i $N.webm -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -c:v libx264 -crf 23 -c:a aac -movflags +faststart $N.mp4

         echo "$OPTARG.mp4 Criado! ";;

      \?) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
done



